name: Test DingTalk Notification

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: å‘é€é’‰é’‰é€šçŸ¥
        uses: mingcai-toolkit/dingtalk-action@v1.0.1
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          secret:  ${{ secrets.DINGTALK_SECRET }}
          message: "å…¶ä»–é¡¹ç›®æ„å»ºæˆåŠŸ ğŸ‰"
          at_mobiles: "13800000000"
          markdown: "false"
          title: "é€šçŸ¥"
